Add Contact Form
codeforgreenville/hackgreenville-com pull request #112
Opened 2022-03-02 04:32 UTC by oliviasculley

This is my first time using PHP, so please let me know if there's anything that should be done differently or changed about this PR. Thank you!

## Features
- Adds contact form that sends slack message to a configured channel
- Contact form uses [hcaptcha](https://hcaptcha.com) with [Scyllaly/hcaptcha](https://github.com/Scyllaly/hcaptcha) to avoid spam.
- Also adds `laravel/slack-notification-channel`.

## Configuration
1. Generate a new Slack webhook URL for the specified channel and set the `SLACK_CONTACT_WEBHOOK` environment variable
2. Register a new HCaptcha account and add the sitekey and secret to the `HCAPTCHA_SITEKEY` and `HCAPTCHA_SECRET` environment variables.
3. Try out the new contact form!

## Issues
Closes #46 

## Preview
![Screenshot 2022-03-01 at 23-25-10 Hackgreenville - A Developer Community in the Greenville SC Area](https://user-images.githubusercontent.com/88074048/156294840-50d25f16-a65d-4407-af88-084900a55300.png)
![Screenshot 2022-03-01 at 23-06-37 Hackgreenville - A Developer Community in the Greenville SC Area](https://user-images.githubusercontent.com/88074048/156294850-4047e86e-0553-4d64-8fe7-a7a856d8c465.png)
Message preview:
![2022-03-01_23-03-1646195230](https://user-images.githubusercontent.com/88074048/156295005-31c45f3a-00bd-41fe-a6ea-4237852a3da1.png)

2022-03-03 02:17 UTC, zach2825 requested changes
Thank you for contributing to the project, sorry if my feedback is excessive.

- Can you move the resources/views/contact.blade.php into the contact directory so it stays grouped with the other contact form stuff?

2022-03-03 02:17 UTC, zach2825 commented on app/Http/Controllers/ContactController.php
> +        $validator = Validator::make(
In this version of larval you can do this validation area like this, see what you think 

```php
        $request->validate([
            'name' => 'required|max:255',
            'contact' => 'required|email:rfc,dns',
            'message' => 'required|max:5000',
            'h-captcha-response' => 'required|HCaptcha'
        ]);
```

or you can remove the condition from line 40 to 44 by appending `->validate();` to the end of your Validator::make call on line 38 like here https://laravel.com/docs/8.x/validation#automatic-redirection

2022-03-03 02:21 UTC, zach2825 commented on app/Http/Controllers/ContactController.php
> +        $validator = Validator::make(
For the validation stuff, when you need special lang support and want to do it easily. You can create a Form Request class
https://laravel.com/docs/9.x/validation#creating-form-requests

I've been using them more and more because they create re-usability and it does a lot of automatic stuff for you.

2022-03-03 15:53 UTC, allella commented
My meta description changes from #111 have been merged in, so you should be able to sync up with develop and add a custom meta description to the new page / view

```
@section('title', 'Contact HackGreenville')
@section('description', 'Send non-spammy questions or comments to the HackGreenville community.')
```

2022-03-04 02:46 UTC, oliviasculley commented
Thank you for suggesting `laravelcollective/html`! I figured there was probably a better way to do the inputs but wasn't sure if there was something that I should add.
I also added `form-groups` to the inputs, so hopefully they should take more advantage of Bootstrap.

I also originally created a custom request, but wasn't sure if it was too verbose and then turned it into the facade :sweat_smile:. It's back to a full request now though :smile: 

Unfortunately, it seemed that laravel collective's form builder possibly defaults to an `http` url, so I used the workaround in this issue: https://github.com/LaravelCollective/html/issues/447#issuecomment-576193331

2022-03-04 12:55 UTC, zach2825 approved these changes
Good job the contact form looks great and thank you for making the other changes in the controller and such, I didn't test actually submitting the contact request. But, it looks like it will work as long as we add the slack settings. 

:100:

2022-03-04 12:56 UTC, zach2825 commented
Whoops, I approved it already. But, would you be able to remove the text-center class from the form? You can remove most of the classes from the form it'll continue to look good. 
![image](https://user-images.githubusercontent.com/4049321/156767398-30692355-640c-4a1a-b0fe-12a94bfce715.png)

2022-03-05 04:49 UTC, oliviasculley commented
Removed some more classes, and this is what it looks like now
![Screenshot 2022-03-04 at 23-49-08 Hackgreenville - A Developer Community in the Greenville SC Area](https://user-images.githubusercontent.com/88074048/156868402-21a50dfa-5df9-4f6c-a195-1067689c6dd3.png)

2022-06-02 15:29 UTC, allella commented
This may come in handy as the Typeform has hit it's monthly submission limit, as seen in #114 

@Soulfire86 has been moderating the invites, so pinging him here too.

2022-06-07 23:45 UTC, allella commented
@Soulfire86 it sounds like there are options to have a contact form Slack integration go to an email, to a channel, and possibly even a private chat (assuming our free tier allows such things).  Thoughts for a direction for @oliviasculley  ?

2022-06-08 01:16 UTC, allella approved these changes

2022-06-08 01:21 UTC, oliviasculley commented on resources/views/contact/submitted.blade.php
> +@section('title', 'Hackgreenville - A Developer Community in the Greenville SC Area')
These should be updated!

2022-06-08 01:21 UTC, oliviasculley commented on resources/views/contact.blade.php
> +@section('title', 'Hackgreenville - A Developer Community in the Greenville SC Area')
These should be updated!

2022-06-08 02:29 UTC, allella commented
This came up in today's Code For Greenville meeting. 

I was initially figuring this contact form would dump into some channel in the HG Slack where anybody subscribed to the channel would see it and help co-moderate.

That sounds nice in the ideal case, but then edge cases cross the mind, like a disgruntled member posts to the contact form to report another member.  You might have someone venting and not realizing it goes straight to a public channel.

Perhaps a "Warning Label" on the form would make it clear the contents are for public moderation, but maybe this goes to a moderator. IDK.

2022-08-18 21:00 UTC, zach2825 commented
This has been reviewed at length I'm merging this :100:

2022-08-18 21:00 UTC, merged